
ALTER TABLE users ADD COLUMN IF NOT EXISTS rebill_id VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS card_last4 VARCHAR(4);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS is_recurrent BOOLEAN DEFAULT false;
