ALTER TABLE users
  ADD COLUMN IF NOT EXISTS grade VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS goal VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS exam_type VARCHAR(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS exam_subject VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS exam_date DATE DEFAULT NULL;
